#' One hundred simulated iris-like species
#'
#' An "iris gone wild" dataset: 100 simulated species with 50 observations
#' each (5,000 rows), generated by perturbing the original iris measurements
#' with species-level effects. Useful for trying out x-axis chunking on a
#' boxplot with far too many levels for a single panel.
#'
#' @format A data frame with 5,000 rows and 5 variables:
#' \describe{
#'   \item{Species}{Simulated species name, a factor with 100 levels.}
#'   \item{Sepal.Length, Sepal.Width, Petal.Length, Petal.Width}{Simulated
#'   measurements in cm, following the iris distributions plus species
#'   effects.}
#' }
#' @source Simulated from [ggplot2::diamonds]'s companion dataset
#'   [datasets::iris]; see `data-raw/iris100.R` for the generating code.
"iris100"

#' Large diamonds sample
#'
#' A random sample of 5,000 rows from `ggplot2::diamonds`, for demonstrating
#' continuous-axis chunking without needing the full 54k-row data set.
#'
#' @format A data frame with 5,000 rows and the usual diamonds variables
#'   (carat, cut, color, clarity, depth, table, price, x, y, z).
#' @source Random sample (seed 2026) of [ggplot2::diamonds].
"diamonds_sample"
